# Generated by Django 5.1.3 on 2025-04-05 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('Artist Spotlights', 'Artist Spotlights'), ('Album Reviews', 'Album Reviews'), ('Hip-Hop News', 'Hip-Hop News'), ('Mixtape Madness', 'Mixtape Madness'), ('Lyric Breakdowns', 'Lyric Breakdowns'), ('Throwback Thursdays', 'Throwback Thursdays'), ('Bars of the Week', 'Bars of the Week'), ('Video Drops', 'Video Drops'), ('Hip-Hop Culture', 'Hip-Hop Culture'), ('Behind the Beat', 'Behind the Beat'), ('Podcasts & Interviews', 'Podcasts & Interviews'), ('Rap Battles & Cyphers', 'Rap Battles & Cyphers'), ('Rising Stars', 'Rising Stars')], max_length=50, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_img')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
